services:
  chronocat-docker:
    image: lhpmain/llonebot-docker
    tty: true
    container_name: llonebot-docker
    restart: always
    ports:
      - "5900:5900"       #vnc默认端口
     # - "6081:6081"       #noVNC默认端口
      - "3000:3000"    
      - "3001:3001"       # 留给反向
    environment:
      - TZ=Asia/Shanghai
      - VNC_PASSWD=vncpasswd
    volumes:
      - ./LLOneBot1/LiteLoader/:/opt/QQ/LiteLoader/
      - ./LLOneBot1/:/opt/QQ/resources/app/LiteLoaderQQNT/data/LLOneBot/
      # 未固化QQ数据 当前仅固化LiteLoader
